import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const fontPair = localFont({
  // USING : Sora for bold-medium, Switzer for regular-extralight
  src: [
    {
      path: './../public/fonts/sora/Sora-Bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: './../public/fonts/sora/Sora-SemiBold.otf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: './../public/fonts/sora/Sora-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './../public/fonts/switzer/Switzer-Regular.otf',
      weight: '400',
      style: 'regular',
    },
    {
      path: './../public/fonts/switzer/Switzer-Light.otf',
      weight: '300',
      style: 'light',
    },
    {
      path: './../public/fonts/switzer/Switzer-Extralight.otf',
      weight: '200',
      style: 'extralight',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPair.className}`}
      >
        {children}
      </body>
    </html>
  );
}
